export const ENV = {
  APP_NAME: (import.meta as any).env.VITE_APP_NAME as string,
  API_BASE_URL: (import.meta as any).env.VITE_API_BASE_URL as string,
  MAP_DEFAULT_LAT: Number((import.meta as any).env.VITE_MAP_DEFAULT_LAT),
  MAP_DEFAULT_LNG: Number((import.meta as any).env.VITE_MAP_DEFAULT_LNG),
  MAP_DEFAULT_ZOOM: Number((import.meta as any).env.VITE_MAP_DEFAULT_ZOOM),
  MAP_TILE_URL: (import.meta as any).env.VITE_MAP_TILE_URL as string,
  MAP_TILE_URL_LIGHT: (import.meta as any).env.VITE_MAP_TILE_URL_LIGHT as string,
  MOCK_DELAY_MIN: Number((import.meta as any).env.VITE_MOCK_API_DELAY_MIN),
  MOCK_DELAY_MAX: Number((import.meta as any).env.VITE_MOCK_API_DELAY_MAX),
  ENABLE_MOCK: (import.meta as any).env.VITE_ENABLE_MOCK_API === 'true',
  TOAST_DURATION: Number((import.meta as any).env.VITE_TOAST_DURATION),
  PAGE_SIZE: Number((import.meta as any).env.VITE_DEFAULT_PAGE_SIZE),
  AUTH_KEY: (import.meta as any).env.VITE_AUTH_STORAGE_KEY as string,
  THEME_KEY: (import.meta as any).env.VITE_THEME_STORAGE_KEY as string,
  FIREBASE: {
    API_KEY: (import.meta as any).env.VITE_FIREBASE_API_KEY as string,
    AUTH_DOMAIN: (import.meta as any).env.VITE_FIREBASE_AUTH_DOMAIN as string,
    PROJECT_ID: (import.meta as any).env.VITE_FIREBASE_PROJECT_ID as string,
    STORAGE_BUCKET: (import.meta as any).env.VITE_FIREBASE_STORAGE_BUCKET as string,
    MESSAGING_SENDER_ID: (import.meta as any).env.VITE_FIREBASE_MESSAGING_SENDER_ID as string,
    APP_ID: (import.meta as any).env.VITE_FIREBASE_APP_ID as string,
  },
} as const;
